---
- name: Gohugo | include OS-specific variables.
  ansible.builtin.include_vars: darwin.yml

- name: Gohugo | update facts.
  ansible.builtin.set_fact:
    gohugo_download_url: "{{ __gohugo_download_url }}"
    gohugo_download_extended_url: "{{ __gohugo_download_extended_url }}"

- name: Gohugo | download base hugo.
  ansible.builtin.unarchive:
    src: "{{ gohugo_download_url }}"
    dest: "{{ __gohugo_destination_unarchive }}"
    remote_src: true
  when: not gohugo_extended

- name: Gohugo | download extended hugo.
  ansible.builtin.unarchive:
    src: "{{ gohugo_download_extended_url }}"
    dest: "{{ __gohugo_destination_unarchive }}"
    remote_src: true
  when: gohugo_extended

- name: Gohugo | copy hugo binary.
  ansible.builtin.copy:
    src: "{{ __gohugo_destination_unarchive }}/hugo"
    dest: "{{ __gohugo_installation_path }}/hugo"
    owner: root
    group: wheel
    mode: "0755"
    remote_src: true
